# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/cross_compile.yml

name: Release

on: [push, pull_request]

# on:
#   create:
#     tags:
#       - "v*"

jobs:
  build:
    name: Build
    runs-on: [ubuntu-18.04]
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
