# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/cross_compile.yml

name: Release

on: [push, pull_request]

# on:
#   create:
#     tags:
#       - "v*"

jobs:
  build:
    name: Build
    runs-on: [ubuntu-18.04]
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: "build artifact"
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: "upload artifact"
        uses: actions/upload-artifact@v1
        # see https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#sharing-data-between-workflow-runs
        with:
          name: test
          path: math-homework
  create-release:
    name: Release
    runs-on: [ubuntu-18.04]
    steps:
      -  # see: https://github.com/actions/upload-release-asset
      -  # create new release
      -  # download all artifacts and upload them to the release

